IMS/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import redirect_user, LandingPageView
from dashboards.views import DashboardView


admin.site.site_header = "Tracker MIS Admin"
admin.site.site_title = "Tracker MIS Admin Portal"
admin.site.index_title = "Welcome to Tracker MIS Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('companies/', include('companies.urls', namespace='home')),
    path('inventory/', include('inventory.urls', namespace="inventory")),
    path('customers/', include('customers.urls', namespace="cusotmers")),
    path('vehicles/', include('vehicles.urls', namespace="vehicles")),
    path('installations/', include('installations.urls', namespace="installations")),
   # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboards/',include('dashboards.urls', namespace="dashboards")),
    path('configurations/',include('configurations.urls', namespace="configurations")),
    path('leads/',include('leads.urls', namespace="leads")),
    path('redirect/', redirect_user, name='redirect'),
    
]

vehicles/urls.py
from django.urls import path
from . import views

app_name = 'vehicles'

urlpatterns = [
    path('', views.VehicleListView.as_view(), name='vehicle_list'),
    path('create/', views.VehicleCreateView.as_view(), name='vehicle_create'),
    path('<int:pk>/', views.VehicleDetailView.as_view(), name='vehicle_detail'),
    path('<int:pk>/update/', views.VehicleUpdateView.as_view(), name='vehicle_update'),
    path('<int:pk>/delete/', views.VehicleDeleteView.as_view(), name='vehicle_delete'),
]

vehicles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from companies.models import Company
from customers.models import Customer
from inventory.models import TrackerDevice, Sim
from django.conf import settings

# Create your models here.
class Vehicle(models.Model):
    RegistrationNumber = models.CharField(max_length=255)
    Make = models.CharField(max_length=255)
    Model = models.CharField(max_length=255)
    EngineNumber = models.CharField(max_length=255)
    ChesisNumber = models.CharField(max_length=255)
    Color = models.CharField(max_length=255)
    
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='vehicle_items', null=True)
    trackerDevice = models.ForeignKey(TrackerDevice, on_delete=models.CASCADE, related_name='vehicle_items', null=True)
    sim = models.ForeignKey(Sim, on_delete=models.CASCADE, related_name='vehicle_items', null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='vehicle_items')
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='vehicle_items')
    isTrackerInstalled = models.BooleanField(default=False)
    def __str__(self):
        return self.RegistrationNumber

vehicles/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Vehicle
from companies.models import Company


class VehicleListView(LoginRequiredMixin, ListView):
    model = Vehicle
    template_name = 'vehicles/vehicle_list.html'
    context_object_name = 'vehicle_list'
    paginate_by = 10

    def get_queryset(self):
        company = self.request.user.company
        return Vehicle.objects.filter(company=company)


class VehicleCreateView(LoginRequiredMixin, CreateView):
    model = Vehicle
    template_name = 'vehicles/vehicle_form.html'
    fields = ('RegistrationNumber', 'Make', 'Model', 'EngineNumber', 'ChesisNumber', 'Color', 'customer', 
              'trackerDevice', 'sim', 'isTrackerInstalled' )
             
    success_url = reverse_lazy('vehicles:vehicle_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.company = self.request.user.company
        return super().form_valid(form)





class VehicleDetailView(DetailView):
    model = Vehicle
    template_name = 'vehicles/vehicle_detail.html'
    context_object_name = 'vehicle'

class VehicleUpdateView(LoginRequiredMixin, UpdateView):
    model = Vehicle
    template_name = 'vehicles/vehicle_form.html'
    fields = ('RegistrationNumber', 'Make', 'Model', 'EngineNumber', 'ChesisNumber', 'Color')
    success_url = reverse_lazy('vehicles:vehicle_list')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


class VehicleDeleteView(LoginRequiredMixin, DeleteView):
    model = Vehicle
    template_name = 'vehicles/vehicle_confirm_delete.html'
    success_url = reverse_lazy('vehicles:vehicle_list')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)

vehicles/templates/vehicles/vehicle_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Confirm deletion of {{ object }}</h1>
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
    <a href="{% url 'vehicles:vehicle_list' %}">Cancel</a>
  </form>
{% endblock %}

vehicles/templates/vehicles/vehicle_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Vehicle Detail</h4>
        </div>
        <div class="card-body">
          <p><strong>Registration Number:</strong> {{ vehicle.RegistrationNumber }}</p>
          <p><strong>Make:</strong> {{ vehicle.Make }}</p>
          <p><strong>Model:</strong> {{ vehicle.Model }}</p>
          <p><strong>Engine Number:</strong> {{ vehicle.EngineNumber }}</p>
          <p><strong>Chesis Number:</strong> {{ vehicle.ChesisNumber }}</p>
          <p><strong>Color:</strong> {{ vehicle.Color }}</p>
          <div class="mt-3">
            <a href="{% url 'vehicles:vehicle_list' %}" class="btn btn-primary btn-sm">Back to List</a>
            <a href="{% url 'vehicles:vehicle_update' vehicle.pk %}" class="btn btn-success btn-sm">Edit</a>
            <a href="{% url 'vehicles:vehicle_delete' vehicle.pk %}" class="btn btn-danger btn-sm">Delete</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

vehicles/templates/vehicles/vehicle_form.html
{% extends 'base.html' %}

{% block content %}
  
 <div class="main_content_iner ">
 <div class="container-fluid p-0 sm_padding_15px">
<div class="row" >

<div  class="col">

</div>
<div  class="col-lg-6">

 <div class="white_card card_height_100 mb_30">
 <div class="white_card_body">
<h2>{% if form.instance.pk %}Edit{% else %}Create{% endif %} Vehicle</h2>
<form method='post'>
{% csrf_token %}
{% load crispy_forms_tags %}
{{ form|crispy }}
<button type='submit' class="btn btn-primary">Save</button>
</form>
<hr />
</div>
</div>
</div>
<div  class="col">
</div>

</div>
</div>
</div>
{% endblock %}

vehicles/templates/vehicles/vehicle_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid mt-3">
  <div class="card">
    <div class="card-header">
      <h5 class="card-title">Vehicle List</h5>
      <a href="{% url 'vehicles:vehicle_create' %}" class="btn btn-primary btn-sm float-right">Add Vehicle</a>
    </div>
    <div class="card-body">
      {% if vehicle_list %}
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Registration Number</th>
            <th scope="col">Make</th>
            <th scope="col">Model</th>
            <th scope="col">Engine Number</th>
            <th scope="col">Chesis Number</th>
            <th scope="col">Color</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for vehicle in vehicle_list %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ vehicle.RegistrationNumber }}</td>
            <td>{{ vehicle.Make }}</td>
            <td>{{ vehicle.Model }}</td>
            <td>{{ vehicle.EngineNumber }}</td>
            <td>{{ vehicle.ChesisNumber }}</td>
            <td>{{ vehicle.Color }}</td>
            <td>
              <a href="{% url 'vehicles:vehicle_detail' vehicle.id %}" class="btn btn-success btn-sm">View</a>
              <a href="{% url 'vehicles:vehicle_update' vehicle.id %}" class="btn btn-primary btn-sm">Edit</a>
              <a href="{% url 'vehicles:vehicle_delete' vehicle.id %}" class="btn btn-danger btn-sm">Delete</a>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="8" class="text-center">No vehicles found.</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
      <p>No vehicles found.</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}