IMS/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import redirect_user, LandingPageView
from dashboards.views import DashboardView


admin.site.site_header = "Tracker MIS Admin"
admin.site.site_title = "Tracker MIS Admin Portal"
admin.site.index_title = "Welcome to Tracker MIS Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('companies/', include('companies.urls', namespace='home')),
    path('inventory/', include('inventory.urls', namespace="inventory")),
    path('customers/', include('customers.urls', namespace="cusotmers")),
    path('vehicles/', include('vehicles.urls', namespace="vehicles")),
    path('installations/', include('installations.urls', namespace="installations")),
   # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboards/',include('dashboards.urls', namespace="dashboards")),
    path('configurations/',include('configurations.urls', namespace="configurations")),
    path('leads/',include('leads.urls', namespace="leads")),
    path('redirect/', redirect_user, name='redirect'),
    
]

configurations/urls.py
from django.urls import path
from . import views
from .views import (
    DepartmentListView,
    DepartmentCreateView,
    DepartmentUpdateView,
    DepartmentDetailView,
    DepartmentDeleteView,
)
app_name = 'configurations'

urlpatterns = [
    path('cities/', views.CityListView.as_view(), name='city_list'),
    path('cities/create/', views.CityCreateView.as_view(), name='city_create'),
    path('cities/<int:pk>/', views.CityUpdateView.as_view(), name='city_update'),
    path('cities/<int:pk>/delete/', views.CityDeleteView.as_view(), name='city_delete'),
    
    path('subscriptions/', views.SubscriptionListView.as_view(), name='subscription_list'),
    path('subscriptions/create/', views.SubscriptionCreateView.as_view(), name='subscription_create'),
    path('subscriptions/<int:pk>/', views.SubscriptionUpdateView.as_view(), name='subscription_update'),
    path('subscriptions/<int:pk>/delete/', views.SubscriptionDeleteView.as_view(), name='subscription_delete'),

    path('departments/', DepartmentListView.as_view(), name='department_list'),
    path('departments/create/', DepartmentCreateView.as_view(), name='department_create'),
    path('departments/update/<int:pk>/', DepartmentUpdateView.as_view(), name='department_update'),
    path('departments/detail/<int:pk>/', DepartmentDetailView.as_view(), name='department_detail'),
    path('departments/delete/<int:pk>/', DepartmentDeleteView.as_view(), name='department_delete'),

    path('provinces/', views.ProvinceListView.as_view(), name='province-list'),
    path('provinces/create/', views.ProvinceCreateView.as_view(), name='province-create'),
    path('provinces/<int:pk>/update/', views.ProvinceUpdateView.as_view(), name='province-update'),
    path('provinces/<int:pk>/', views.ProvinceDetailView.as_view(), name='province-detail'),
    path('provinces/<int:pk>/delete/', views.ProvinceDeleteView.as_view(), name='province-delete'),

    path('customer-group/', views.CustomerGroupListView.as_view(), name='customer-group-list'),
    path('customer-group/create/', views.CustomerGroupCreateView.as_view(), name='customer-group-create'),
    path('customer-group/update/<int:pk>/', views.CustomerGroupUpdateView.as_view(), name='customer-group-update'),
    path('customer-group/delete/<int:pk>/', views.CustomerGroupDeleteView.as_view(), name='customer-group-delete'),

    path('insurance/', views.InsuranceListView.as_view(), name='insurance-list'),
    path('insurance/create/', views.InsuranceCreateView.as_view(), name='insurance-create'),
    path('insurance/update/<int:pk>/', views.InsuranceUpdateView.as_view(), name='insurance-update'),
    path('insurance/delete/<int:pk>/', views.InsuranceDeleteView.as_view(), name='insurance-delete'),

    path('banks/', views.BankListView.as_view(), name='bank-list'),
    path('banks/create/', views.BankCreateView.as_view(), name='bank-create'),
    path('banks/update/<int:pk>/', views.BankUpdateView.as_view(), name='bank-update'),
    path('banks/delete/<int:pk>/', views.BankDeleteView.as_view(), name='bank-delete'),

    path('vehicle-makes/', views.VehicleMakeListView.as_view(), name='vehicle-make-list'),
    path('vehicle-makes/create/', views.VehicleMakeCreateView.as_view(), name='vehicle-make-create'),
    path('vehicle-makes/<int:pk>/update/', views.VehicleMakeUpdateView.as_view(), name='vehicle-make-update'),
    path('vehicle-makes/<int:pk>/delete/', views.VehicleMakeDeleteView.as_view(), name='vehicle-make-delete'),

    path('vehicle-model/', views.VehicleModelListView.as_view(), name='vehicle-model-list'),
    path('vehicle-model/create/',views.VehicleModelCreateView.as_view(), name='vehicle-model-create'),
    path('vehicle-model/<int:pk>/update/', views.VehicleModelUpdateView.as_view(), name='vehicle-model-update'),
    path('vehicle-model/<int:pk>/delete/',views.VehicleModelDeleteView.as_view(), name='vehicle-model-delete'),

    path('packages/', views.PackageListView.as_view(), name='package-list'),
    path('packages/create/', views.PackageCreateView.as_view(), name='package-create'),
    path('packages/update/<int:pk>/', views.PackageUpdateView.as_view(), name='package-update'),
    path('packages/delete/<int:pk>/', views.PackageDeleteView.as_view(), name='package-delete'),

    path('complain-types/', views.ComplainTypesListView.as_view(), name='complain-types-list'),
    path('complain-types/create/', views.ComplainTypesCreateView.as_view(), name='complain-types-create'),
    path('complain-types/update/<int:pk>/', views.ComplainTypesUpdateView.as_view(), name='complain-types-update'),
    path('complain-types/delete/<int:pk>/', views.ComplainTypesDeleteView.as_view(), name='complain-types-delete'),


]

configurations/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .forms import (DepartmentForm, 
                    ProvinceForm,CustomerGroupForm, InsuranceForm, BankForm, 
                    VehicleMakeForm, VehicleModelForm, PackageForm, ComplainTypesForm
                    
                    )
from .models import (
    Cities, Subscriptions,Province,
    Department, CustomerGroup, Insurance, Bank,
    VehicleMake, VehicleModel, Package, ComplainTypes, 
)

class CityListView(ListView):
    model = Cities
    template_name = 'configurations/city_list.html'


class CityCreateView(CreateView):
    model = Cities
    fields = ['city']
    template_name = 'configurations/city_form.html'
    success_url = reverse_lazy('configurations:city_list')


class CityUpdateView(UpdateView):
    model = Cities
    fields = ['city']
    template_name = 'configurations/city_form.html'
    success_url = reverse_lazy('configurations:city_list')


class CityDeleteView(DeleteView):
    model = Cities
    template_name = 'configurations/city_confirm_delete.html'
    success_url = reverse_lazy('configurations:city_list')


class SubscriptionListView(ListView):
    model = Subscriptions
    template_name = 'configurations/subscription_list.html'
    context_object_name = 'subscriptions'

class SubscriptionCreateView(CreateView):
    model = Subscriptions
    fields = ['subscription', 'days', 'price']

    template_name = 'configurations/subscription_form.html'
    success_url = reverse_lazy('configurations:subscription_list')


class SubscriptionUpdateView(UpdateView):
    model = Subscriptions
    fields = ['subscription']
    template_name = 'configurations/subscription_form.html'
    success_url = reverse_lazy('configurations:subscription_list')


class SubscriptionDeleteView(DeleteView):
    model = Subscriptions
    template_name = 'configurations/subscription_confirm_delete.html'
    success_url = reverse_lazy('configurations:subscription_list')


class DepartmentListView(ListView):
    model = Department
    context_object_name = 'departments'
    template_name = 'configurations/department/department_list.html'

class DepartmentCreateView(CreateView):
    model = Department
    form_class = DepartmentForm
    template_name = 'configurations/department/department_create.html'
    success_url = reverse_lazy('configurations:department_list')

class DepartmentUpdateView(UpdateView):
    model = Department
    form_class = DepartmentForm
    template_name = 'configurations/department/department_create.html'
    success_url = reverse_lazy('configurations:department_list')

class DepartmentDetailView(DetailView):
    model = Department
    context_object_name = 'department'
    template_name = 'configurations/department/department_detail.html'

class DepartmentDeleteView(DeleteView):
    model = Department
    context_object_name = 'department'
    template_name = 'configurations/department/department_confirm_delete.html'
    success_url = reverse_lazy('configurations:department_list')


class ProvinceListView(ListView):
    model = Province
    template_name = 'configurations/province/province_list.html'
    context_object_name = 'provinces'

class ProvinceCreateView(CreateView):
    model = Province
    template_name = 'configurations/province/province_create.html'
    form_class = ProvinceForm
    success_url = reverse_lazy('configurations:province-list')

class ProvinceUpdateView(UpdateView):
    model = Province
    template_name = 'configurations/province/province_update.html'
    form_class = ProvinceForm
    success_url = reverse_lazy('configurations:province-list')

class ProvinceDetailView(DetailView):
    model = Province
    template_name = 'configurations/province/province_detail.html'
    context_object_name = 'province'

class ProvinceDeleteView(DeleteView):
    model = Province
    template_name = 'configurations/province/province_confirm_delete.html'
    success_url = reverse_lazy('configurations:province-list')

class CustomerGroupListView(ListView):
    model = CustomerGroup
    template_name = 'configurations/customergroup/customer_group_list.html'
    context_object_name = 'customer_group_list'

class CustomerGroupCreateView(CreateView):
    model = CustomerGroup
    template_name = 'configurations/customergroup/customer_group_create.html'
    form_class = CustomerGroupForm
    success_url = reverse_lazy('configurations:customer-group-list')

class CustomerGroupUpdateView(UpdateView):
    model = CustomerGroup
    template_name = 'configurations/customergroup/customer_group_update.html'
    form_class = CustomerGroupForm
    success_url = reverse_lazy('configurations:customer-group-list')

class CustomerGroupDeleteView(DeleteView):
    model = CustomerGroup
    template_name = 'configurations/customergroup/customer_group_confirm_delete.html'
    success_url = reverse_lazy('configurations:customer-group-list')

class InsuranceListView(ListView):
    model = Insurance
    template_name = 'configurations/insurance/insurance_list.html'

class InsuranceCreateView(CreateView):
    model = Insurance
    template_name = 'configurations/insurance/insurance_create.html'
    form_class = InsuranceForm

class InsuranceUpdateView(UpdateView):
    model = Insurance
    template_name = 'configurations/insurance/insurance_update.html'
    form_class = InsuranceForm

class InsuranceDeleteView(DeleteView):
    model = Insurance
    template_name = 'configurations/insurance/insurance_confirm_delete.html'
    success_url = '/configurations/insurance/'

class BankListView(ListView):
    model = Bank
    template_name = 'configurations/bank/bank_list.html'
    context_object_name = 'banks'


class BankCreateView(CreateView):
    model = Bank
    form_class = BankForm
    template_name = 'configurations/bank/bank_create.html'
    success_url = reverse_lazy('configurations:bank-list')


class BankUpdateView(UpdateView):
    model = Bank
    form_class = BankForm
    template_name = 'configurations/bank/bank_update.html'
    success_url = reverse_lazy('configurations:bank-list')


class BankDeleteView(DeleteView):
    model = Bank
    template_name = 'configurations/bank/bank_confirm_delete.html'
    success_url = reverse_lazy('configurations:bank-list')

class VehicleMakeListView(ListView):
    model = VehicleMake
    template_name = 'configurations/vehiclemake/vehicle_make_list.html'

class VehicleMakeCreateView(CreateView):
    model = VehicleMake
    form_class = VehicleMakeForm
    template_name = 'configurations/vehiclemake/vehicle_make_create.html'
    success_url = reverse_lazy('configurations:vehicle-make-list')

class VehicleMakeUpdateView(UpdateView):
    model = VehicleMake
    form_class = VehicleMakeForm
    template_name = 'configurations/vehiclemake/vehicle_make_update.html'
    success_url = reverse_lazy('configurations:vehicle-make-list')

class VehicleMakeDeleteView(DeleteView):
    model = VehicleMake
    template_name = 'configurations/vehiclemake/vehicle_make_confirm_delete.html'
    success_url = reverse_lazy('configurations:vehicle-make-list')

class VehicleModelListView(ListView):
    model = VehicleModel
    template_name = 'configurations/vehiclemodel/vehicle_model_list.html'

class VehicleModelCreateView(CreateView):
    model = VehicleModel
    form_class = VehicleModelForm
    template_name = 'configurations/vehiclemodel/vehicle_model_create.html'
    success_url = reverse_lazy('configurations:vehicle-model-list')

class VehicleModelUpdateView(UpdateView):
    model = VehicleModel
    form_class = VehicleModelForm
    template_name = 'configurations/vehiclemodel/vehicle_model_update.html'
    success_url = reverse_lazy('configurations:vehicle-model-list')

class VehicleModelDeleteView(DeleteView):
    model = VehicleModel
    template_name = 'configurations/vehiclemodel/vehicle_model_confirm_delete.html'
    success_url = reverse_lazy('configurations:vehicle-model-list')

class PackageListView(ListView):
    model = Package
    template_name = 'configurations/package/package_list.html'


class PackageCreateView(CreateView):
    model = Package
    form_class = PackageForm
    template_name = 'configurations/package/package_create.html'
    success_url = reverse_lazy('configurations:package-list')


class PackageUpdateView(UpdateView):
    model = Package
    form_class = PackageForm
    template_name = 'configurations/package/package_update.html'
    success_url = reverse_lazy('configurations:package-list')


class PackageDeleteView(DeleteView):
    model = Package
    template_name = 'configurations/package/package_confirm_delete.html'
    success_url = reverse_lazy('configurations:package-list')

class ComplainTypesListView(ListView):
    model = ComplainTypes
    template_name = 'configurations/complain_types_list.html'

class ComplainTypesCreateView(CreateView):
    model = ComplainTypes
    form_class = ComplainTypesForm
    template_name = 'configurations/complain_types_create.html'
    success_url = reverse_lazy('configurations:complain-types-list')

class ComplainTypesUpdateView(UpdateView):
    model = ComplainTypes
    form_class = ComplainTypesForm
    template_name = 'configurations/complain_types_update.html'
    success_url = reverse_lazy('configurations:complain-types-list')

class ComplainTypesDeleteView(DeleteView):
    model = ComplainTypes
    template_name = 'configurations/complain_types_confirm_delete.html'
    success_url = reverse_lazy('configurations:complain-types-list')

configurations/templates/configurations/department/department_create.html
{% extends 'base.html' %}

{% block content %}
<div class="main_content_iner ">
    <div class="container-fluid p-0 sm_padding_15px">
        <div class="row justify-content-left">
            <div class="col-lg-4">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                              <h2>{% if object %}Update{% else %}Create{% endif %} Department</h2>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        <div class="card-body">
              
              <form method="post">
                {% csrf_token %}
                {% load crispy_forms_tags %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Save</button>
              </form>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>  
{% endblock %}

configurations/templates/configurations/department/department_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="main_content_iner">
    <div class="container-fluid p-0 sm_padding_15px">
      <div class="row">
        <div class="col">
          <div class="white_card card_height_100 mb_30">
            <div class="white_card_body">
              <h2>Department Details</h2>
              <table class="table table-bordered">
                <tbody>
                  <tr>
                    <th>ID</th>
                    <td>{{ department.id }}</td>
                  </tr>
                  <tr>
                    <th>Name</th>
                    <td>{{ department.name }}</td>
                  </tr>
                  <tr>
                    <th>Description</th>
                    <td>{{ department.description }}</td>
                  </tr>
                  <tr>
                    <th>Date</th>
                    <td>{{ department.date }}</td>
                  </tr>
                </tbody>
              </table>
              <a href="{% url 'configurations:department_update' department.id %}" class="btn btn-primary">Edit</a>
              <a href="{% url 'configurations:department_delete' department.id %}" class="btn btn-danger">Delete</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

configurations/templates/configurations/department/department_list.html
{% extends 'base.html' %}

{% block content %}
<div class="main_content_iner ">
    <div class="container-fluid p-0">
        <div class="row justify-content-right">
            <div class="col-lg-6">
                <div class="white_card card_height_100 mb_30">
                    <div class="white_card_header">
                        <div class="box_header m-0">
                            <div class="main-title">
                                <h3 class="m-0">Cities</h3>
                            </div>
                        </div>
                    </div>
                    <div class="white_card_body">
                        <div class="QA_section">
                            <div class="white_box_tittle list_header">
                                {% comment %} <h4>shorting Arrow</h4> {% endcomment %}
                                <div class="box_right d-flex lms_block">
                                    {% comment %} <div class="serach_field_2">
                                        <div class="search_inner">
                                            <form Active="#">
                                                <div class="search_field">
                                                    <input type="text" placeholder="Search content here...">
                                                </div>
                                                <button type="submit"> <i class="ti-search"></i> </button>
                                            </form>
                                        </div>
                                    </div> {% endcomment %}
                                    <div class="add_button ms-2">
                                        <a href="{% url 'configurations:department_create' %}" class="btn btn-primary">Add Department</a>
                                    </div>
                                </div>
                            </div>
    
                            <div class="QA_table mb_30">
                                <!-- table-responsive -->
    <table class="table lms_table_active3 ">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Date</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for department in departments %}
                    <tr>
                      <td>{{ department.id }}</td>
                      <td>{{ department.name }}</td>
                      <td>{{ department.description }}</td>
                      <td>{{ department.date }}</td>
                      <td>
                        <a href="{% url 'configurations:department_detail' department.id %}">View</a> |
                        <a href="{% url 'configurations:department_update' department.id %}">Edit</a> |
                        <a href="{% url 'configurations:department_delete' department.id %}">Delete</a>
                      </td>
                    </tr>
                  {% empty %}
                    <tr>
                      <td colspan="5">No departments available.</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
        </div>
        </div>
        </div>
        </div>
        
        </div>
        </div>
        </div>
{% endblock %}